- data/bangs.json
It's dead https://wiki.openstreetmap.org/wiki/OpenLinkMap#Download
> remove openlinkmap

- README.md
Just a one-line readme tweak.
Thanks!
> Add deployment note per discussion

- data/bangs.json
bookshop.org allow you to purchase books, while supporting local booksellers.
> Added bookshop

- data/bangs.json
[Printables](https://www.printables.com/) is a well-established website which is (mainly) used for sharing and downloading models for 3D printing.
> Add bang for searching 3D models on printables.com

- data/bangs.json
https://oda.com/no/
Norwegian grocery store that sells everyday groceries and dinner dishes online
> Add !oda for oda.com

- data/bangs.json
Adds `!meny` for Norwegian grocery store Meny (https://meny.no/)
> Add !meny for meny.no

- data/bangs.json
https://www.steamgriddb.com/search/grids
> Add SteamGridDB

- README.md
- data/bangs.json
- data/kagi_bangs.json
Android Code Search allows for fast searching of the entire Android OS codebase
> Add Android Code Search

- data/bangs.json
There’s no search engine anymore on ploum.net
> Making ploum.net a native Kagi bang

- README.md
- data/bangs.json
- data/kagi_bangs.json
https://kagifeedback.org/d/4132-use-in-as-a-regional-bang-for-india
> Change `!in` bang to a regional bang for India

- .gitignore
- data/bangs.json
It's stylized "YouTube" not "Youtube"
> Fix consistency with YouTube branding

- data/bangs.json
> Add Bluesky

- data/bangs.json
> kagifeedback.org/d/4280

- data/bangs.json
> Fix Reverse Image Search

- data/bangs.json
> Shorten Google Translate URL

- data/bangs.json
Adds a Manjaro branch compare bang. 
Link to site: https://manjaristas.org/branch_compare
> Add Manjaristas Branch Compare

- data/bangs.json
- Add bang for Prusa E-shop which sells 3D printers and related goods
- Add bang for Prusa Help, a knowledge base for 3D printing
- Remove bang for Prusa Printers which has been replaced by Printables
> Add bangs, remove outdated bang related to Prusa

- data/kagi_bangs.json
I noticed that google has !g24 and !gyears so figured kagi could use with those as well
> Add !24 and !year bangs to kagi bangs

- data/bangs.json
Saw a Tweet about adding Grok as a search engine for your browser and thought it would be cool to have a bang for that as well. 
https://x.com/512x512/status/1855674088666337301
> Add Grok (x.com)

- data/bangs.json
Hi Kagi team,
Remember about 30 minutes ago when we were discussing where to get lunch, and we tried using !doordash, and it didn't work?
Yeah.
> Add DoorDash

- data/bangs.json
Resolves [this Kagi Feedback post](https://kagifeedback.org/d/5844)
> Fix MSDN bang

- data/bangs.json
> Updated old osm forum links 

- data/bangs.json
> Added substack bang search

- data/bangs.json
This pull request adds the !kpr bang for Kagi Translate's proofread feature. 
It translates the user input from Automatic to Proofread.
> Add Kagi Translate Proofread

- data/bangs.json
- data/kagi_bangs.json
- changed !gif to direct to kagi gif search
- add !kfd, based on !kf (kagifeedback but only discussions. meant for snap usage)
- add !hac (home assistant community forum)
> change !gif, add !kfd, add !hac

- data/bangs.json
> Fix XE bang

- data/bangs.json
Add bang to search directly in the autohotkey docs
> Add autohotkey v2 docs

- data/bangs.json
repology/repology-webapp@0da996f3c1dc0bebdfbd0e773b153dc3f40183d7
> fix repology ("/metapackages" -> "/projects")

- data/bangs.json
this bang could be very handy for developers that work with chromium (me included)
> Add a bang for Chromium Code Search

- data/bangs.json
No idea why this one exists, how it got added to the DDG bangs, but it's dead and it's porn (I assume the cognates are true), so I don't I think it should be here.
> remove dead porn? site

- data/bangs.json
https://bgp.tools is a site for checking various routing information, similar to !bgp but a lot more effective at what it does
> add bgp.tools bangs (!bgpt, !bgptools)

- data/bangs.json
Felo and Ithy are both AI chatbots that I think should have bangs.
> Add Felo and Ithy

- data/bangs.json
Simple Icons is a collection with over 3200 SVG icons for popular brands: https://simpleicons.org/
> Add Simple Icons

- data/bangs.json
The old bangs seem to have stopped working, I believe within the last day or so.
> Update Yahoo Finance bangs

- data/bangs.json
Replaced sub category with AI Chatbots instead of Tools
Replaced domain with grok.com instead of x.com
Replace URL template with the URL template for grok.com
> Update the Grok bang

- data/bangs.json
Added the [openrouter](https://openrouter.ai/) website.
> add openrouter.ai

- data/bangs.json
This is a repository for fans of Brandon Sanderson books of Brandon's quotes, called "Words of Brandon" or WoBs, which are used to confirm or reveal information about the books. [The website](https://wob.coppermind.net/) is called the Arcanum, and it holds WoBs, so I added bangs for !wobs and !arcanum.
> Add wob.coppermind.net bangs

- data/bangs.json
[Microsoft Store](https://apps.microsoft.com) (formerly Windows Store)
+ new bangs 
+ update of outdated data
> Update Microsoft Store bangs

- data/bangs.json
> Add bangs for historical research websites

- data/bangs.json
NixOS package/option search with better UX
> Add MyNixOS

- data/bangs.json
This pull request updates the !kpr bang URL for Kagi Translate's proofread feature.
> Update Kagi Translate Proofread URL

- data/bangs.json
> Add grep.app

- data/bangs.json
> Fix Allocine bang

- data/bangs.json
`ansible-galaxy`
`ansiblemod`
`galaxy`
`ansible`
> Fix ansible related bangs

- data/bangs.json
this is adding figura docs as a bang, and adding the figura wiki as a bang.
(this is my first fork ever, please scrutinize the code as i might've messed up😅)
> Figura Wiki/Figura Documentation added

- data/bangs.json
- UCSC to browse the genome
- Genereviews as an encyclopedia for genetics diseases
- Decipher to correlate genetics mutation to human diseases
Thanks !
> Genomics tools

- data/bangs.json
Q @nobodywasishere I see some amazon entries like the austria one have .... a lot of bangs... 
But most other amazon bangs don't.
Do you want to remove some from the austria one / what bangs would you want me to add to the other amazon bangs so they're atleast closer to consistency?
(also , is it okay that I added germany to the austria one like that? there was no german amazon bang yet)
> Changes to amazon bangs

- data/kagi_bangs.json
Seems like a decent amount of them were missing
fixes https://kagifeedback.org/d/8565-please-add-a-regional-bang-for-chile
EDIT:
OOOOH that's why these were missing, cause they overlapped with existing bangs... :thinking: 
i'll check
> complete all regions kagi_bangs
