data/bangs.json
Jisho.org requires `%20`-encoded spaces (e.g. https://jisho.org/search/search%20engine instead of https://jisho.org/search/search+engine).
Resolves https://kagifeedback.org/d/3245-jisho-bang-encodes-spaces-incorrectly
=> Fix Jisho.org URL encoding

data/bangs.json
The Hollow Knight Wiki on Fandom (Formerly Wikia) has moved to hollowknight.wiki: https://hollowknight.fandom.com/wiki/Hollow_Knight_Wiki:Moving_from_Fandom
=> Hollow Knight Fandom/Wikia -> Hollow Knight Wiki

data/bangs.json
- Terraria Wiki: https://forums.terraria.org/index.php?threads/new-official-terraria-wiki-launches-today.111239/
- Don't Starve Wiki: https://www.reddit.com/r/dontstarve/comments/15z7bbl/dont_starve_wiki_moved_to_wikigg/
- Dungeons & Dragons Wiki: https://dungeons.fandom.com/wiki/Forum:We%27re_Moving
- Hearthstone Wiki: https://www.reddit.com/r/hearthstone/comments/16l9vzo/hearthstone_wiki_has_migrated_from_fandom_to/
- Noita Wiki: https://www.reddit.com/r/noita/comments/xnxx22/noita_wiki_has_migrated_to_wikigg/
- Thorium Wiki (Linked from mod forum post https://forums.terraria.org/index.php?threads/the-thorium-mod.40788/)
- PUBG: https://www.reddit.com/r/PUBATTLEGROUNDS/comments/127ln33/pubg_wiki_is_moving_to_wikigg/
- Toontown Rewritten Wiki: …
=> Update various wikis

data/bangs.json
The existing bang was using a domain that no longer functions (`gen.lib.rus.ec`); I've modified it to use a domain that functions (`libgen.rs`).
I got the new domain from this [reddit announcement](https://old.reddit.com/r/libgen/comments/15p8h24/announcement_access_library_genesis_via_the/), and [LibGen's Wikipedia page](https://en.wikipedia.org/wiki/Library_Genesis) also shows it.
LibGen categorizes most of its data into three buckets; each one is searched via a distinct URL. I've added one bang for each:
1. `!libg` - searches  "Non-Fiction"; behaviorally identical to `!genesis`, but shorter and syntactically consistent with the next two (which must be longer because of their category specifiers)
2. `!libgfic` - searches "Fiction"
3. `!libgsci` - searches "Scientific Articles"
=> Fix and flesh out LibGen bangs

data/bangs.json
Mangadex search query changed and now use the usual `?q=` query parameter.
=> fix: mangadex search query

data/bangs.json
See https://www.uspto.gov/about-us/news-updates/uspto-launches-new-patent-public-search-tool-and-webpage:
"Based on the advanced Patents End-to-End (PE2E) search tool USPTO examiners use to identify prior art, this free, cloud-based platform combines the capabilities of four existing search tools **scheduled to be retired in September 2022**: Public-Examiner’s Automated Search Tool (PubEAST), Public-Web-based Examiner’s Search Tool (PubWEST), **Patent Full-Text and Image Database (PatFT)**, and Patent Application Full-Text and Image Database (AppFT)."
=> patft.uspto.gov is retired, and bang no longer works

data/bangs.json
Expresso is a flagship weekly publication of the Impresa Group for Portugal.
=> Add Expresso search engine to bangs.json

data/bangs.json
Per the discussion [here](https://github.com/kagisearch/bangs/pull/8#issuecomment-1959648030), this adds additional bangs for the CourtListener website:
- `cl-law` is a mirror of the `courtlistener` bang to make it shorter.
- `cl-audio` searches our oral argument audio database
- `cl-recap` is a mirror of the `recap` bang, to make it available under the `cl-` namespace we're using for other bangs.
With this complete, we'll have five bangs:
- `cl-recap` and `recap` will search the RECAP Archive.
- `cl-law` and `courtlistener` will search our case law.
- `cl-audio` will search our audio files.
Thank you for making this possible!
=> Add more bangs for CourtListener

data/bangs.json
apkpure.com has been down since January. It is now accessible through apkpure.net
https://apkpure.net/news/important-notice-regarding-apkpure-com-site
=> Fix APKPure

data/bangs.json
Adds `!matprat` for [matprat.no](https://www.matprat.no/), a website for recipes and articles from the Norwegian Information Office for Eggs and Meat.
=> Add matprat.no

data/bangs.json
Updated URL templates for Finnish, Swedish and Norwegian bangs, and fixed capitalization.
Also removed the Danish bang, since it's just a redirect to the Swedish website with no option to change to Danish.
=> Fix adlibris.com

data/bangs.json
Fixed the URL template for the `!finn` bang for [finn.no](https://www.finn.no/) (Norwegian classified advertisements website).
Also added some "subbangs" for the subsections "Torget" (marketplace) and "Jobb" (recruitment ads)-
=> Fix finn.no + subbangs

data/bangs.json
Adds `!mazemap` for the MazeMap web application at [use.mazemap.com](https://use.mazemap.com/). This is a popular service for indoor maps and wayfinding at universities, hospitals and office buildings.
=> Add !mazemap

data/bangs.json
Updated the URL template for `!dnt` ([dnt.no](https://www.dnt.no/)), where they have chosen to betray the beloved letter ø...
=> Fix `!dnt`

data/bangs.json
This PR fixes broken query url for Namu wiki.
=> fix: Fix query url for Namu wiki

README.md, data/bangs.json
Adds the `!vinmonopolet` bang for [vinmonopolet.no](https://www.vinmonopolet.no), the website for the Norwegian Wine Monopoly. Basically the Norwegian equivalent of `!systembolaget`.
=> Add vinmonopolet.no

data/bangs.json
The search link has been broken for quite a while.
`!allegro airpods` -> http://allegro.pl/listing.php/search?string=airpods -> 404 page
https://allegro.pl/listing?string=airpods -> proper listing
=> fix: update allegro.pl

data/bangs.json
Android Code Search is a nice tool to search in the Android codebase.
It also includes AndroidX, Android Studio and Android-llvm.
The bang is `csa` for Code Search Android because `acs` was already taken.
It matches the 3 first letters of the subdomain and the tld.
=> add Android Code Search

data/bangs.json
the !botb bang appends site:battleofthebits.org to a query, which leads to broken links. an example query is "!botb test", which transforms into "test site:battleofthebits.org", which results in all broken links
the current domain is battleofthebits.com - please see https://battleofthebits.com/academy/GroupThread/35044/we+may+have+lost+our+.org. "!botb test" should instead translate to "test site:battleofthebits.com"
=> Update BotB bang

data/bangs.json
The previous (broken) URL template would always respond with a 404 error.
The new URL template correctly responds with search results.
=> Fix Meijer URL template

data/bangs.json
The !metacritic bang was leading to an error page. This replaces its URL to match the !mc bang, which works.
=> Fix !metacritic bang

.bundle/config, .github/workflows/validate_json.yml, .gitignore, .vscode/settings.json, Gemfile, Gemfile.lock, data/assistant_bangs.json, data/bangs.json, data/kagi_bangs.json, spec/bangs_spec.rb
This pull requests adds some RSpec tests for use in CI, allowing for better verification of bangs. These do things such as:
- Verifying the domain field matches the domain in the template field
- Ensuring no overlapping/duplicate bangs within each bangs file, and between the bangs files
As well, this PR adds the assistant bangs, and modifies some bangs to remove duplicates.
=> Add RSpec tests + assistant bangs

data/bangs.json
Typst is “A new markup-based typesetting system that is powerful and easy to learn.”
This PR adds a bang to search its documentation `!typst`, as well as one to look for packages `!typstu`.
In the future, I intend to change the documentation search to use Typst's own site directly, but at the moment you can't pass query parameters, so, Kagi with `site:` it is.
=> Add bangs for Typst

data/bangs.json
Adds `!tine` for recipes and articles from the Norwegian dairy product cooperative Tine (https://www.tine.no)
=> Add !tine for tine.no

README.md, data/bangs.json
Adds bangs for:
- [Nixpkgs Search](https://search.nixos.org/packages)
- [NixOS Options Search](https://search.nixos.org/options)
- [Noogle (Nix Function Search)](https://noogle.dev)
=> Add Nixpkgs, NixOS Options, and Noogle bangs

data/bangs.json
Adding a bang search for https://www.listennotes.com/, a full text podcast search engine.
=> Adding listennotes.com

data/bangs.json
The existing query structure is outdated. Cycling 74' have updated their querying to use this new format. Can be verified with this:
https://cycling74.com/search?q=docs
=> update cycling74 bang

data/bangs.json
The old wiki is deprecated (and was outdated and unmaintained). A new official wiki has takes its place under the official nixos domain.
(also took the liberty to put the 3 nixos wiki entries next to eachother)
=> Update NixOS wiki

data/bangs.json
Codeberg.org is a FOSS alternative to GitHub, hosting over 125,000 open source projects.
This PR adds a `!codeberg` bang to search through all public repositories hosted on codeberg.org.
=> Add codeberg.org search

data/assistant_bangs.json, data/bangs.json, spec/bangs_spec.rb
I noticed duplicate triggers in the same file while parsing the JSON for another purpose. This PR updates the RSpec tests to detect this scenario, and fixes up the duplicate triggers.
The change in 7e43d305ddbd371e42025201d44047b8af380945 assumes that this scenario should be invalid. The `uniq` caused it to deduplicate triggers in the same JSON file. It would only detect duplicate triggers if they appeared across JSON files.
The following commits are consolidating the duplicates as best as I could.
=> Update RSpec tests to detect duplicate triggers in same file and fix duplicate triggers

data/bangs.json
Fixes multiple bangs for [ordbokene.no](https://ordbokene.no/) (formerly ordbok.uib.no)
=> Fix ordbokene.no

data/bangs.json
Fixes **[kagifeedback#3941](https://kagifeedback.org/d/3941-appstore-bang-doesnt-send-user-to-results-page)**
=> fix: inconsistency in appstore bang

data/bangs.json
By default, the `/` in a GitHub repo path will be URL encoded, resulting in an incorrect URL.
=> Do not URL encode GitHub repos

data/bangs.json
This PR is a draft and is unlikely to be final, as some of these changes may require further discussion. The PR aims to make the existing wikipedia bangs more consistent by using `w[country code]` as a trigger and changing the site name. It also adds missing wikipedias with more than 30 active users, according to [this](https://en.wikipedia.org/wiki/List_of_Wikipedias) list. The following wikipedias are not included due to conflicts with existing triggers:
- Thai Wikipedia
- Tamil Wikipedia
- Serbo-Croatian Wikipedia
- Bosnian Wikipedia
- Tagalog Wikipedia
- Kurdish Wikipedia
- Tajik Wikipedia
- Haitian Creole Wikipedia
- Somali Wikipedia
- Amharic Wikipedia
- Sundanese Wikipedia
- Interlingue Wikipedia
- Interlingua Wikipedia
Some of the issues that I would like to discuss:
- This change …
=> Draft: more consistent wikipedia bangs

data/bangs.json
Pexels uses `%20`-encoded spaces (e.g. https://www.pexels.com/search/search%20engine/ instead of https://www.pexels.com/search/search+engine/).
=> Fix Pexels URL encoding

data/bangs.json
The University of North Carolina at Chapel Hill Library recently updated its website, breaking the existing `!unclib` bang. This PR fixes it.
=> Update URL template for UNC-CH library search

data/bangs.json
This adds a bang to search the official wiki for [Predecessor](https://www.predecessorgame.com/), a MOBA by Omeda.  The tag chosen, `!pred`, is a very common community abbreviation for the game's title.
=> Add a bang for the official Predecessor wiki.

data/bangs.json
It's under /w/ which is common for Mediawiki.
=> data/bangs: fix nixos wiki url

data/bangs.json
Old query: https://docs.scipy.org/doc/scipy/reference/search.html?q=sparse&check_keywords=yes&area=default
New query: https://docs.scipy.org/doc/scipy/search.html?q=sparse&check_keywords=yes&area=default
=> Fix Scipy URL

data/bangs.json
Google Music shutdown in 2020 (https://9to5google.com/2020/12/03/google-play-music-dead/), and the redirect to YouTube Music breaks the query as it simply redirects to the base URL
=> Remove Google Music

data/bangs.json
Fixes the `!caniuse` bang to use query strings for the search parameters (e.g. https://caniuse.com/?search=grid instead of https://caniuse.com/#search=grid), which is how the site now operates by default. The old hash links still work but are legacy and rewritten to the new format.
Also fixes space-encoding as Can I Use… natively uses %20-encoding for spaces rather than pluses.
=> Fix Can I use… bang

data/bangs.json
JAX and FLAX are machine learning frameworks for Python made by Google, this searches their documentation.
=> Add JAX and FLAX docs

data/bangs.json
Adding 2 websites:
OpenCritic, it's like MetaCritic, but specifically for games. They don't have a search inside the site, so i'm adding it as a site filter bang. (www.opencritic.com)
KProfiles, it's a K-Pop site with group profiles (www.kprofiles.com).
=> Add Open Critic and KProfiles

data/bangs.json
=> Add AI tools

data/bangs.json
I am working on cleaning up the bangs for my app. Sharing my work:
- Separated into four commits so the resulting diffs are easier to understand.
- Each commit message is a log of the changes that were made.
- The commit messages may be pasted into https://multi-launch.leftium.com (click "Edit" first) to easily confirm the new and old URLs behave the same. (I spot tested several URLs; many bangs don't even work and should just be removed...)
- The script used to make the changes: [clean-bangs.ts](https://github.com/Leftium/bangtastic/blob/c38f318c02059bfb9a18b079287607b83faf7101/bangs/clean-bangs.ts)
- To simplify the diffs between changes, all URLs were trimmed and unescaped.
- Some URLs had been escaped, then escaped again, and again...
- I find the unescaped URLs easier to read, and …
=> Clean up bangs.

data/bangs.json
Add an alternate domain for trigger `yle` that searches contents of domain yle.fi. haku.yle.fi domain only contains the search application for yle.fi ("<span lang="fi">haku</span>" means "search" in Finnish).
Also, update the query parameters to those currently in use.
=> Add alternate domain for Yle

data/kagi_bangs.json
I know it's A LOT of bangs, but I also noticed that google has bangs like !gnbe which searches google news for belgium.
So figured it would be nice if Kagi had the same.
So had everything single region that is listed in Kagi News converted to bangs.
Also I checked, none of these bangs conflict with any of the existing bangs in kagi_bangs.json, bangs.json or assistant_bangs.json
(do I need to create kagifeedback's for these and just ask them to be marked as done? I'm not sure if the kagi changelog relies on kagifeedback's or if this would be manually added?)
=> Add all Kagi News regions as bangs

data/bangs.json
I'll be honest, I made gpt do all of this (I just quickly checked it didn't change any things it shouldn't have).
I noticed that some of the ones that were changed are no longer using working websites but that's a check for later I guess
=> Replace most of the 'kagi search' site: entries with proper names and domains

data/bangs.json
(The main public transport operator in Northern Ireland)
Supports searching bus timetables by route number, eg https://www.translink.co.uk/timetables?Name=238 - Unfortunately can't cover searching by destination/stop, as those use an internal ID where the name parameter does nothing, eg. https://www.translink.co.uk/timetables?LocationId=10000055&Name=The+moon
The same could also be added for train timetables, but given that it requires the exact full line name (eg `?Name=Bangor+line&TransportMode=Train` is required instead of `?Name=Bangor&TransportMode=Train`), and that the rail network barely exists here, I've left it out for now.
=> Add Translink NI timetable search

data/bangs.json
New url: https://www.chicagotribune.com/?s={{{s}}}
Uses default chicago tribune search options
=> Fix Chicago Tribune bang URL

data/bangs.json
[Query.rs](https://query.rs/) is a very convenient search engine for querying rust documentation. It has about 250 stars on [GitHub](https://github.com/huhu/query.rs).
=> Add query.rs

data/bangs.json
I changed protonmail to tools instead of search, is that ok or should it be search or maybe search private? I don't really get those categories yet
There doesn't seem to be much consitentcy for email services.
Tuta mail is 'social'. gmail is it's own category (fair enough), outlook is also search, fastmail is tools, yahoo mail is "Search (Private)"
=> Add kde, osm, proton bangs

data/bangs.json, spec/bangs_spec.rb
In #147, nobodywasishere suggested that we should change the checks to ignore %23 in URI encoding. Well, I did it and fixed the bang. Also, hopefully this also fixes the bang (as it's broken right now)
=> %23 hack fixes

data/bangs.json
Propose `!cdev` as a bang for the Cloudflare Developer documentation.
=> Add Cloudflare Developer Docs bang

data/bangs.json
Updated `royalroadl` to `royalroad` and also the `keyword` to `title` since that provides better search results when only using a bang as the search.
=> updated royalroad

README.md, data/bangs.json
Added `Claude`, `T3 Chat` and `Le Chat` AI chatbots, as well the `AI Chatbots` subcategory that now includes the aforementioned and `ChatGPT` (I didn't find any other).
=> Add AI Chatbots

data/bangs.json
following the pattern for !camlib, this will search the University of Edinburgh Libraries DiscoverEd catalogue
=> Add UoE library catalogue

README.md, data/bangs.json
Removed the slash that was breaking the URL. Also fixed the metadata.
=> Fix nu.nl URL template

data/bangs.json
This PR introduces two additional bangs `!hfd` and `!hfd` for searching [huggingface hub](https://huggingface.co/) for datasets and models (there's no unified search). The website is really popular in the AI sphere which I believe justifies the bangs being upstreamed.
=> Add huggingface search bangs

data/bangs.json
Adds JS-adjacent tech sites:
- [Raycast](https://www.raycast.com/store) - popular Mac Spotlight replacement
- [Icônes](https://icones.js.org/) - icon aggregator from a prolific JS maintainer
- [njt](https://njt.vercel.app/) - convenient proxy to popular npm tools
Tested in https://github.com/dmlls/yang ✅
=> Add Raycast, Icônes, and njt

data/bangs.json
There are several tracking query string parameters assumedly left over from the DuckDuckGo import. These tracking parameters are not only inaccurate but also provide no benefit to the user so should be removed.
=> Remove DuckDuckGo query string references

data/bangs.json
The `!bang` and `!bangs` meta-bangs still leads to a search of DuckDuckGo's bangs, which the Kagi bangs are slowly diverging from. This PR replaces that with the unofficial (but [referenced in the Kagi docs](https://help.kagi.com/kagi/features/bangs.html)) [community bang explorer](https://kbe.smaertness.net).
=> Search Kagi bangs

data/bangs.json
Added `!bugs`, `!melon`, `!genie`, and `!vibe` to allow for quick searches on the largest South Korean music streaming providers.
=> Add Korean music streaming providers

data/bangs.json
it's been [shut down since 2020](https://www.theverge.com/2020/5/19/21263584/walmart-jet-shutdown-amazon-online-shopping-3-billion-2016), bangs redirect to walmart.com with no search term actually used
*(discovered it when going through one-letter bang list in alphabetical order)*
=> Remove bangs for jet.com

data/bangs.json
!download, !software, and !shareware bangs break the rule of not being common words, [as mentioned in the readme](https://github.com/kagisearch/bangs#:~:text=are%20not%20OK.-,The%20trigger,-must%20be%20specific). furthermore, none of them worked. download.cnet.com is also known to be spreading adware & malware (seriously, just open the page).
this PR also removes bangs for ES and UK version of cnet. ES version of CNET hasn't been active since 2017 and moved over to the [other domain with no search functionality](https://cnetenespanol.com/), while UK bang duplicates the search URL for the main website. neither of them worked, too.
cnet is not culturally important enough to claim the !c bang (especially if you compare it to websites like google or wikipedia), so i removed it also.
while …
=> Remove outdated & spammy CNET bangs, fix the URL for main one

data/bangs.json
zalando doesn't seem to be culturally important enough to have a single letter bang, since it's a EU-only clothing reseller
=> Remove !z bang for zalando

data/bangs.json
https://www.tv.com seems to be inactive, and according to Wikipedia (without any sources though), [has been since 2021](https://en.wikipedia.org/wiki/TV.com).
Not sure what to do with the !tv bang though, only services that I can think of are TheTVDB and Thingiverse
=> tv.com has shut down, move !tv bang to imdb

data/bangs.json
* Added !mdresourcepacks, !mddatapacks, and !mdshaders (now available from Modrinth)
* Ordered them in this list to match the order on the Modrinth website
* cfe959b: Added "mr" variants of the Modrinth bangs (they're more intuitive)
~~By the way: Is there a reason "md" was picked instead of "mr"? I also think there should be an alias system or fuzzy-search on the homepage, so you can use i.e. `!modrinth` to find these more easily...~~
=> Update Modrinth bangs

data/bangs.json
this is a cleanup of some low hanging fruits: domains which currently return a NXDOMAIN, as well all of the onion services that have bangs, which are all v2 style URLs that have not been supported for a while now (https://support.torproject.org/onionservices/v2-deprecation/)
=> remove dead bangs

data/bangs.json
The current URL for ARIN only returns result for IP searches. This change makes it so that you can search different stuff and still get a relevant result (e.g. AS36459).
=> use more general search url for !arin

data/bangs.json
The URI query changed from `q` to `query`.
=> Fix Cloudflare Developer Doc bang

data/bangs.json
This PR adds two bangs `!stdict` `!사전`(dictionary in Korean[^1]) for Standard Korean Language Dictionary[^2][^3] maintained by the National Institute of Korean Language[^4].
[^1]: https://translate.kagi.com/?text=사전
[^2]: https://stdict.korean.go.kr
[^3]: https://en.wikipedia.org/wiki/Standard_Korean_Language_Dictionary
[^4]: https://korean.go.kr
=> Add !stdict and !사전 for Standard Korean Language Dictionary

data/bangs.json
figured it'd make sense for this to exist since "bsky" is already there
=> Add a "bluesky" bang for bluesky

data/bangs.json
Previously, the bang always searched for “time” regardless of the query.
---
This is the URL that Lifeprint’s search form uses (https://www.lifeprint.com in the upper left). It looks like the `ie` and `sa` parameters are not needed, but I left them in since the web site uses them.
=> Fix Lifeprint bang

data/bangs.json
store.docker.com redirects to hub.docker.com
=> !docker: replace Docker Store with Docker Hub

data/bangs.json
https://rubydocs.org has been brought offline. I now pointed !rb to !ruby which searches ruby-lang.org
I also updated !ruby to have a correct alternate domain set
=> move !rb to ruby-lang.org

data/bangs.json
I'm following the pattern for library catalogues, but the RS has three separate ones. The first two are normal keyword searches. The Fellow search is by surname.
Searching the Fellows by text is possible, but not very useful. If you need the search for Fellows to follow the keyword model, change `Surname` to `(text)` as in the previous queries.
Respectfully submitted,
=> added Royal Society Collection Catalogues

data/bangs.json
The official wiki for Warframe has moved, so update all the associated bangs. The DE Warframe wikia bang has been left as there is no German equivalent of the new wiki. Also updated the categories to better reflect these are video game related bangs. Official announcement of the Wiki's move is [here](https://www.warframe.com/news/devstream-184-overview).
=> Update Warframe related bangs

data/bangs.json
Hi,
tl;dr: This is a simple maintenance update.
The website for CVEs is being renovated and migrated to a new domain. Migrating the bang to the new domain will prevent breaking the bang when the previous site goes down.
Please let me know if fixes should be applied.
=> fix(bangs): update `!cve` to use new website

data/bangs.json
change !posix as [The Open Group Base Specifications, Issue 7, 2018 Edition](https://publications.opengroup.org/standards/unix/c181) = [IEEE Std 1003.1-2017](https://ieeexplore.ieee.org/document/8277153) is superseded by [The Open Group Base Specifications, Issue 8](https://publications.opengroup.org/standards/unix/c243) = [IEEE Std 1003.1-2024](https://ieeexplore.ieee.org/document/10555529)
=> change !posix from Issue 7 to Issue 8

data/bangs.json
VIAF changed its formatting a while ago, making `!viaf` useless. This updates the URL to make it work again. Let me know if I am doing this right!
=> update VIAF search url

data/bangs.json
The TARDIS wiki forked from wikia/fandom a few months ago, this updates the bang to search on the new wiki instead of the Fandom one. It additionally updates `!dww` which also lead to the fandom wiki.
=> use updated, non-fandom (forked) wiki for TARDIS

data/bangs.json
- unified the name for the english version: `English Wikipedia/Wikipedia (English)/Wikipedia` -> `Wikipedia`
- removed misleading bangs: `w-es` was actually english wikipedia despite being called `Wikipedia (in Spanish)`
- fixed wikispecies bang, as it previously linked to regular wikipedia instead
- updated all english wikipedia bang urls to be the same
- unified subcategories for regular wikipedia bangs
- `template` -> `wikitemplate` & `module` -> `wikimodule`, because common words aren't allowed to be bangs. also updated their titles
- grouped all english bangs together because previously they were spread all across the psuedo "wikipedia section" of the file
i'd also remove the "encyclopedia" bang if i was to strictly follow the common word rule, but i think it can have a pass because …
=> Clean up English Wikipedia bangs

data/bangs.json
identical alternative bang is named “Le Chat”, so i figured it makes sense to rename this one to be “Le Chat” too
=> Fix mistral bang's subcategory and name

data/bangs.json
The previous search to Abe's Market was broken for months (seems to no longer exists and the domain was taken over).
=> bangs: replace abe to amazon belgium

data/bangs.json
the current url setup for the `!mario` bang does not work correctly. For instance, searching `!mario luigi's mansion` on Kagi brings the user to `https://www.mariowiki.com/Luigi%27s%2Bmansion`, a broken page. This PR makes the `!mario` bang target the same url as the correctly working `!mariowiki` bang.
=> fix broken !mario bang, making url same as !mariowiki

data/bangs.json
[`player_search.cgi`](https://www.baseball-reference.com/pl/player_search.cgi) seems to no longer exist
=> Fix broken !baseball, make same as !bbref

data/bangs.json
This PR updates all Genius-related bangs with an appropriate title, url, and category
rapgenius = genius, it was rebranded [over 11 years ago](https://en.wikipedia.org/wiki/Genius_(company)#Relaunch_as_%22Genius%22_and_expanded_funding)
=> Update outdated genius.com bangs

data/bangs.json
`https://bandcamp.com/tag/<tag>` now returns a permanent redirect to `/discover/<tag>`
```shell
> curl -I https://bandcamp.com/tag/krautrock
HTTP/2 301
server: nginx
content-type: text/html; charset=UTF-8
location: /discover/krautrock
```
=> Update bctag destination

data/bangs.json
dpm.lol is a site where you can track stats for League of Legends accounts
=> Add DPMLOL
